### ISSUE TITLE
Tela inicial e card para Professores, Empresas Juniores e Equipes de Competição

### ISSUE THREAD

**Issue by izabellaalves** [fga-eps-mds/2023.1-HEART-hub-fga-inovacao#34]
# Tela inicial e card para Professores, Empresas Juniores e Equipes de Competição
## Descrição
Nesta issue, devemos concluir nossa tela inicial e deixá-la acessível para todos os computadores. Na tela inicial devemos ter: seção 1 (contendo a descrição e a logo do site), seção 2 (contendo um resumo de cada disponibilidade do site), footer (contendo um pequeno texto informando que somos um HUB de Inovação da Universidade de Brasília - Campus Gama, e o link pro site da FGA).

Além disso, faremos também as telas de Professores, Empresas Juniores e Equipes de Competição, lembrando que estas três telas terão o mesmo card.
## Tarefas

- [x] Clonar a main deste repositório
- [x] Arrumar a seção 1 
- [x] Integrar a seção 2 na tela Inicio
- [x] Criar o footer 
- [x] Integrar todos estes componentes na tela Início
- [x] Criar o Figma do card das telas
- [x] Criar o card criado no Figma no React e consumir os arquivos Json de Empresas Juniores, Equipes de Competição e Professores
- [ ]

**Comment by lucassouzs** [comment]
# Issue completa
