### ISSUE TITLE
Tela de contatos

### ISSUE THREAD

**Issue by izabellaalves** [fga-eps-mds/2023.1-HEART-hub-fga-inovacao#46]
# Tela de contatos
## Descrição
Para facilitar a comunicação da equipe com o público externo, teremos uma tela de contatos, onde vários meios de contato com a nossa equipe serão disponibilizadas ao usuário.
## Tarefas

- [x] Verificar o design da tela de contatos no Figma da equipe
- [x] Implementar a tela de contatos
- [x] Verificar se a tela de adapta aos outros computadores (obs.: usar REM ao invés de PIXEL)

**Comment by LucasOliveiraDiasMarquesFerreira** [comment]
Tudo concluído, sem conflitos e nenhum problema.
